// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QRdZDw7ENCLYdXWvpep6F6XdV_C3zqY',
    appId: '1:131081968765:web:435aa73058d4d551afe514',
    messagingSenderId: '131081968765',
    projectId: 'battleground-bd225',
    authDomain: 'battleground-bd225.firebaseapp.com',
    storageBucket: 'battleground-bd225.appspot.com',
    measurementId: 'G-WCBVE98DMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3w4XZw5XZ_c7HObUDNzjfyXnLgQsObM',
    appId: '1:131081968765:android:0034955c84cd1fbaafe514',
    messagingSenderId: '131081968765',
    projectId: 'battleground-bd225',
    storageBucket: 'battleground-bd225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsm5ypjuJDmvNXCk4CYHwDm4jEPcGZKrw',
    appId: '1:131081968765:ios:60a57dd255873770afe514',
    messagingSenderId: '131081968765',
    projectId: 'battleground-bd225',
    storageBucket: 'battleground-bd225.appspot.com',
    iosBundleId: 'at.chwe.flutterflavors',
  );
}
